version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      POSTGRES_DB: chillshaker
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local